usb: typec: ucsi: Make UCSI_GLINK select QCOM_PDR_HELPERS
If CONFIG_QCOM_PDR_HELPERS has not been selected, we will run into build
issues, such as

    aarch64-linux-gnu-ld: drivers/usb/typec/ucsi/ucsi_glink.o: in function `ucsi_glink_probe':
    ucsi_glink.c:(.text+0x6ec): undefined reference to `pdr_handle_alloc'
    aarch64-linux-gnu-ld: ucsi_glink.c:(.text+0x70c): undefined reference to `pdr_add_lookup'

Make CONFIG_UCSI_GLINK select CONFIG_QCOM_PDR_HELPERS to fix these.

Fixes: cad8e970fae ("pmic_glink: Add UCSI/PAN prototype")
Signed-off-by: Maximilian Luz <luzmaximilian@gmail.com>